#!/bin/bash
# Copyright (c) 2017 DaSoftver LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

#makes gz file that has everything needed to install Cloudgizer

echo "**"
echo "** Installing Cloudgizer "
echo "**"

#clean and make from scratch so there's no mixing with previous build (that's why we clean)
make clean
make makecld
OUT=$?
if [ $OUT -ne 0 ]; then
    echo "Problem found (0), stopping"
    exit $OUT
fi

# test install_binary right now by installing cld
./make_utility
OUT=$?
if [ $OUT -ne 0 ]; then
    echo "Problem found (4), stopping"
    exit $OUT
fi



