#!/bin/bash
# Copyright (c) 2017 DaSoftver LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

#makes gz file that has everything needed to install Cloudgizer

echo "**"
echo "** Making binary distribution"
echo "**"

#remove temporary directories
rm -rf clddev
mkdir clddev
mkdir clddev/clddist

#clean and make from scratch so there's no mixing with previous build (that's why we clean)
make clean
make
OUT=$?
if [ $OUT -ne 0 ]; then
    echo "Problem found (0), stopping"
    exit $OUT
fi

#list of files to include in installation
export EXELISTSRC="cldgoapp cldpackapp cldbuild cldmakefile libcld.so cld.o libacld.so cld.a cld.h Makefile make_utility mod_cld.o  LICENSE NOTICE "

#copy to a directory we're going to gzip
cp -avrL $EXELISTSRC `pwd`/clddev/clddist
OUT=$?
if [ $OUT -ne 0 ]; then
    echo "Problem found (1), stopping"
    exit $OUT
fi

#tar and gzip so that all is in clddist once unpacked
tar -hcf - -C `pwd`/clddev .  | gzip -9 > clddist.tar.gz
OUT=$?
if [ $OUT -ne 0 ]; then
    echo "Problem found (3), stopping"
    exit $OUT
fi

#check it's okay and remove temporary directory
ls -asl clddist.tar.gz
rm -rf clddev

# concatinate unpacker (stub_binary) with gz file created in make_dist
cat stub_binary clddist.tar.gz >  setup_cld

# test install_binary right now by installing cld
chmod +x ./setup_cld
./setup_cld
OUT=$?
if [ $OUT -ne 0 ]; then
    echo "Problem found (4), stopping"
    exit $OUT
fi

#remove the intermediate artifact
rm -rf clddist.tar.gz
rm -rf clddist

# make installer executable, ready to run
chmod +x setup_cld
ls -asl setup_cld


