#!/bin/bash
# Copyright (c) 2017 DaSoftver LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.


# All in one Cloudgizer setup script. Once you've done it once, you can update cloudgizer binaries by just 
# doing setup_cld.

#check error in each step, make sure process continues with success
function check_error ()
{
	OUT=$1
	PLACE=$2
	if [ $OUT -ne 0 ]; then
		echo "Problem found (${PLACE}), stopping"
		exit $OUT
	fi
}


echo "***"
echo "***"
echo "INSTALLING PROGRAMS AND LIBRARIES"
echo "***"
echo "***"
./setup_env
check_error $? "Error installing programs and libraries"
echo "***"
echo "***"
echo "INSTALLING DATABASE"
echo "***"
echo "***"
./setup_maria
check_error $? "Error installing MariaDB"
echo "***"
echo "***"
echo "INSTALLING POSTFIX"
echo "***"
echo "***"
./setup_postfix
check_error $? "Error installing Postfix"
echo "***"
echo "***"
echo "INSTALLING CLOUDGIZER"
echo "***"
echo "***"
./setup_cld
check_error $? "Error installing Cloudgizer"

